version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./api/Dockerfile  # используем существующий Dockerfile
    container_name: metrics_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app

volumes:
  app_data: 